name: Bloggy
description: Download bloggy
inputs:
  version:
    required: true
    path: the version of the bloggy
runs:
  using: composite
  steps:
    - run: |
        wget https://github.com/nsecho/bloggy/releases/download/v${{ inputs.version }}/bloggy_${{ inputs.version }}_linux_amd64.tar.gz -O - | tar --extract -z
        sed -i 's/outdir: .*/outdir: .\/NSEcho.github.io/g' cfg.yaml
        ./bloggy gen --drafts=false
        cp favicon.ico NSEcho.github.io/assets/
      shell: bash
